EXAMPLEAND-112 changed two way otp into dummy fixed value one + renames
onewelcome/example-app-android pull request #326
Opened 2023-10-06 13:12 UTC by PiotrKlis

2023-10-23 12:58 UTC, aleknow requested changes

2023-10-23 14:58 UTC, aleknow requested changes

2023-10-23 14:58 UTC, aleknow commented on app/src/main/java/com/onegini/mobile/exampleapp/OneginiConfigModel.java
> +  private final String baseURL = "https://mobile-security-proxy.onegini.com";
App2Web url needs to be updated too, as now it won't work

2023-10-24 09:41 UTC, PiotrKlis commented on app/src/main/java/com/onegini/mobile/exampleapp/OneginiConfigModel.java
> +  }
We can take a look at this when we'll be adjusting the SDK configurator on new version parameter.

2023-11-01 13:50 UTC, merged